<?php

namespace STS\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnuaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnuaireRepository extends EntityRepository
{
}
